# Generated by Django 4.0.4 on 2022-07-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, verbose_name='model identifier')),
                ('url', models.CharField(max_length=255)),
                ('score', models.PositiveIntegerField(null=True)),
                ('metrics', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
